# Generated by Django 6.0.1 on 2026-01-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Evento')),
                ('descripcion', models.TextField(verbose_name='Descripción Turística')),
                ('fecha_inicio', models.DateTimeField(verbose_name='Fecha y Hora de Inicio')),
                ('fecha_fin', models.DateTimeField(verbose_name='Fecha y Hora de Fin')),
                ('imagen_portada', models.ImageField(upload_to='eventos/', verbose_name='Foto del Evento')),
                ('lugar_nombre', models.CharField(max_length=100, verbose_name='Nombre del Lugar (Ej. Parque Montalvo)')),
                ('latitud', models.FloatField(verbose_name='Latitud (GPS)')),
                ('longitud', models.FloatField(verbose_name='Longitud (GPS)')),
                ('enlace_vivo', models.URLField(blank=True, null=True, verbose_name='Enlace de Transmisión (YouTube/FB)')),
            ],
        ),
    ]
