# Generated by Django 6.0.1 on 2026-01-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='es_megaevento',
            field=models.BooleanField(default=False, verbose_name='¿Es Megaevento?'),
        ),
        migrations.AddField(
            model_name='evento',
            name='tipo',
            field=models.CharField(choices=[('DESFILE', 'Desfiles y Pregones'), ('CONCIERTO', 'Conciertos y Música'), ('REINA', 'Elección de Reinas'), ('RELIGIOSO', 'Actos Religiosos'), ('CINE', 'Cine en los Barrios'), ('TEATRO', 'Teatro y Cultura'), ('DEPORTE', 'Deportes'), ('BARRIO', 'Eventos Barriales'), ('OTRO', 'Otros')], default='OTRO', max_length=20),
        ),
        migrations.AlterField(
            model_name='evento',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='enlace_vivo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_inicio',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='imagen_portada',
            field=models.ImageField(blank=True, null=True, upload_to='eventos/'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='latitud',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='evento',
            name='longitud',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='evento',
            name='lugar_nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='evento',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
