# Generated by Django 6.0.1 on 2026-01-27 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_evento_es_megaevento_evento_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='imagen_portada',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
