# Generated by Django 6.0.1 on 2026-01-27 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_alter_evento_imagen_portada'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='categoria',
            field=models.CharField(choices=[('DESFILE', 'Desfiles y Pregones'), ('CONCIERTO', 'Conciertos y Música'), ('REINA', 'Elección de Reinas'), ('RELIGIOSO', 'Actos Religiosos'), ('CINE', 'Cine en los Barrios'), ('TEATRO', 'Teatro y Cultura'), ('DEPORTE', 'Deportes'), ('BARRIO', 'Eventos Barriales'), ('OTRO', 'Otros')], default='OTRO', max_length=20),
        ),
    ]
