# Generated by Django 6.0.1 on 2026-01-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_evento_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='imagen_portada',
            field=models.ImageField(blank=True, null=True, upload_to='eventos/', verbose_name='Imagen de Portada'),
        ),
    ]
